# Generated by Django 3.2.24 on 2024-02-27 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('estado', models.IntegerField(choices=[[0, 'soltero'], [1, 'novio'], [2, 'casado'], [3, 'relacion abierta'], [4, 'complicado']])),
                ('passw', models.CharField(max_length=50)),
            ],
        ),
    ]
