# Generated by Django 3.2.24 on 2024-02-29 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_contacto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='log',
        ),
    ]
